### ISSUE TITLE
Refactoring to C#

### ISSUE THREAD

**Issue by santisq** [santysq/Network-IPScanner#1]

**Comment by krzydoug** [comment]
> _No description provided._

I'd like to upvote this but you haven't provided any details. :)

**Comment by santisq** [comment]
> > _No description provided._
> 
> I'd like to upvote this but you haven't provided any details. :)

It's for making a binary module for the `*Async` functions 😅 _soon™_

**Comment by santisq** [comment]
Hey @krzydoug was wondering if you could give me your opinion on which name to use for this parameter: [PSNetScannerCommandBase.cs#L25-L28](https://github.com/santisq/PSNetScanners/blob/1-refactoring-to-c/src/PSNetScanners/Abstractions/PSNetScannerCommandBase.cs#L25-L28). It's essentially the time in ms to wait before outputting a "Timeout" result object. Also open to any suggestions before pushing this to the main branch and then publishing it.
